# Generated by Django 6.0.1 on 2026-06-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0004_alter_orbitentry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orbitentry',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Stable hash used to group identical events (e.g. exceptions)', max_length=32),
        ),
        migrations.AddIndex(
            model_name='orbitentry',
            index=models.Index(fields=['type', 'fingerprint', '-created_at'], name='orbit_orbit_type_ce38f0_idx'),
        ),
    ]
