# Generated by Django 6.0.1 on 2026-06-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0006_backfill_exception_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='orbitentry',
            name='tags',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Comma-wrapped tags for filtering (e.g. ',slow,checkout,')", max_length=255),
        ),
    ]
